PRODUCTS = [
    {
        "product_id": 1,
        "name": "담백한 한과 선물 세트",
        "category": "한과",
        "price": 28000,
        "description": "개별포장된 담백한 맛의 한과 선물 세트",
        "sweetness": 2,
        "packaging": "individual",
        "storage_method": "room",
        "gift_available": True,
    },
    {
        "product_id": 2,
        "name": "꿀 약과 선물 세트",
        "category": "한과",
        "price": 24000,
        "description": "달콤한 꿀 약과를 개별포장한 선물 세트",
        "sweetness": 5,
        "packaging": "individual",
        "storage_method": "room",
        "gift_available": True,
    },
    {
        "product_id": 3,
        "name": "구운 견과 선물 세트",
        "category": "견과",
        "price": 32000,
        "description": "구운 견과를 하나의 용기에 담은 선물 세트",
        "sweetness": 1,
        "packaging": "bulk",
        "storage_method": "room",
        "gift_available": True,
    },
    {
        "product_id": 4,
        "name": "담백한 현미 떡",
        "category": "떡",
        "price": 12000,
        "description": "한 개씩 포장한 일상 간식용 현미 떡",
        "sweetness": 1,
        "packaging": "individual",
        "storage_method": "frozen",
        "gift_available": False,
    },
    {
        "product_id": 5,
        "name": "개별포장 견과 선물 세트",
        "category": "견과",
        "price": 35000,
        "description": "한 봉지씩 나누어 포장한 견과 선물 세트",
        "sweetness": 1,
        "packaging": "individual",
        "storage_method": "room",
        "gift_available": True,
    },
]